"""measure baseline tokens

Revision ID: 9a973932b94d
Revises: c8a40feeda41
Create Date: 2026-09-01 23:20:53.372206
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '9a973932b94d'
down_revision: str | None = 'c8a40feeda41'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # server_default backfills existing rows (these are NOT NULL); the default is
    # then dropped so the ORM default governs new inserts. Without this, upgrading
    # a database that already has queries/source_files rows would fail.
    op.add_column('queries', sa.Column('baseline_tokens', sa.Integer(),
                                       nullable=False, server_default='0'))
    op.add_column('queries', sa.Column('baseline_files', sa.Integer(),
                                       nullable=False, server_default='0'))
    op.add_column('source_files', sa.Column('token_count', sa.Integer(),
                                            nullable=False, server_default='0'))
    op.alter_column('queries', 'baseline_tokens', server_default=None)
    op.alter_column('queries', 'baseline_files', server_default=None)
    op.alter_column('source_files', 'token_count', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_files', 'token_count')
    op.drop_column('queries', 'baseline_files')
    op.drop_column('queries', 'baseline_tokens')
    # ### end Alembic commands ###
