"""initial schema

Revision ID: c8a40feeda41
Revises: 
Create Date: 2026-09-01 21:50:43.238620
"""
from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'c8a40feeda41'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('dataset', sa.String(length=1024), nullable=False),
    sa.Column('recall_at_1', sa.Float(), nullable=False),
    sa.Column('recall_at_3', sa.Float(), nullable=False),
    sa.Column('recall_at_5', sa.Float(), nullable=False),
    sa.Column('recall_at_10', sa.Float(), nullable=False),
    sa.Column('mrr', sa.Float(), nullable=False),
    sa.Column('avg_retrieved_tokens', sa.Float(), nullable=False),
    sa.Column('avg_context_tokens', sa.Float(), nullable=False),
    sa.Column('avg_retrieval_latency_ms', sa.Float(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repositories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('local_path', sa.String(length=1024), nullable=False),
    sa.Column('default_branch', sa.String(length=255), nullable=False),
    sa.Column('indexed_commit_sha', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repositories_name'), 'repositories', ['name'], unique=True)
    op.create_table('indexing_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('from_commit', sa.String(length=64), nullable=True),
    sa.Column('to_commit', sa.String(length=64), nullable=True),
    sa.Column('files_indexed', sa.Integer(), nullable=False),
    sa.Column('files_deleted', sa.Integer(), nullable=False),
    sa.Column('symbols_indexed', sa.Integer(), nullable=False),
    sa.Column('symbols_deleted', sa.Integer(), nullable=False),
    sa.Column('embeddings_created', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('candidates_found', sa.Integer(), nullable=False),
    sa.Column('candidates_selected', sa.Integer(), nullable=False),
    sa.Column('candidate_tokens', sa.Integer(), nullable=False),
    sa.Column('context_tokens', sa.Integer(), nullable=False),
    sa.Column('dropped_tokens', sa.Integer(), nullable=False),
    sa.Column('retrieval_latency_ms', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('language', sa.String(length=32), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('indexed_commit_sha', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'path', name='uq_source_files_repo_path')
    )
    op.create_index('ix_source_files_repo', 'source_files', ['repository_id'], unique=False)
    op.create_table('llm_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cached_input_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('symbols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('language', sa.String(length=32), nullable=False),
    sa.Column('symbol_name', sa.String(length=512), nullable=False),
    sa.Column('qualified_name', sa.String(length=1024), nullable=False),
    sa.Column('symbol_type', sa.String(length=32), nullable=False),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.Column('parent_symbol_id', sa.Integer(), nullable=True),
    sa.Column('source_code', sa.Text(), nullable=False),
    sa.Column('docstring', sa.Text(), nullable=True),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('search_document', sa.Text(), nullable=False),
    sa.Column('fts', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', search_document)", persisted=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_symbol_id'], ['symbols.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_symbols_commit', 'symbols', ['commit_sha'], unique=False)
    op.create_index('ix_symbols_fts', 'symbols', ['fts'], unique=False, postgresql_using='gin')
    op.create_index('ix_symbols_path', 'symbols', ['repository_id', 'file_path'], unique=False)
    op.create_index('ix_symbols_repo', 'symbols', ['repository_id'], unique=False)
    op.create_index('ix_symbols_repo_qualified', 'symbols', ['repository_id', 'qualified_name'], unique=False)
    op.create_index('ix_symbols_repo_type', 'symbols', ['repository_id', 'symbol_type'], unique=False)
    op.create_index('ix_symbols_source_hash', 'symbols', ['source_hash'], unique=False)
    op.create_table('retrieval_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_retrieval_query', 'retrieval_results', ['query_id'], unique=False)
    op.create_table('symbol_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('embedding_model', sa.String(length=255), nullable=False),
    sa.Column('embedding_version', sa.String(length=64), nullable=False),
    sa.Column('embedding_dimension', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol_id', 'embedding_model', 'embedding_version', name='uq_embedding_symbol_model')
    )
    op.create_index('ix_embedding_repo', 'symbol_embeddings', ['repository_id'], unique=False)
    op.create_table('symbol_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('source_symbol_id', sa.Integer(), nullable=False),
    sa.Column('target_symbol_id', sa.Integer(), nullable=True),
    sa.Column('target_name', sa.String(length=1024), nullable=True),
    sa.Column('relationship_type', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_symbol_id'], ['symbols.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_symbol_id'], ['symbols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rel_repo_source', 'symbol_relationships', ['repository_id', 'source_symbol_id'], unique=False)
    op.create_index('ix_rel_repo_target', 'symbol_relationships', ['repository_id', 'target_symbol_id'], unique=False)
    op.create_index('ix_rel_type', 'symbol_relationships', ['relationship_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rel_type', table_name='symbol_relationships')
    op.drop_index('ix_rel_repo_target', table_name='symbol_relationships')
    op.drop_index('ix_rel_repo_source', table_name='symbol_relationships')
    op.drop_table('symbol_relationships')
    op.drop_index('ix_embedding_repo', table_name='symbol_embeddings')
    op.drop_table('symbol_embeddings')
    op.drop_index('ix_retrieval_query', table_name='retrieval_results')
    op.drop_table('retrieval_results')
    op.drop_index('ix_symbols_source_hash', table_name='symbols')
    op.drop_index('ix_symbols_repo_type', table_name='symbols')
    op.drop_index('ix_symbols_repo_qualified', table_name='symbols')
    op.drop_index('ix_symbols_repo', table_name='symbols')
    op.drop_index('ix_symbols_path', table_name='symbols')
    op.drop_index('ix_symbols_fts', table_name='symbols', postgresql_using='gin')
    op.drop_index('ix_symbols_commit', table_name='symbols')
    op.drop_table('symbols')
    op.drop_table('llm_requests')
    op.drop_index('ix_source_files_repo', table_name='source_files')
    op.drop_table('source_files')
    op.drop_table('queries')
    op.drop_table('indexing_runs')
    op.drop_index(op.f('ix_repositories_name'), table_name='repositories')
    op.drop_table('repositories')
    op.drop_table('evaluation_runs')
    # ### end Alembic commands ###
